import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ffb4ab",
        "on-primary-container": "#002a53",
        "surface-tint": "#a5c8ff",
        "surface-container": "#1d2022",
        "primary": "#a5c8ff",
        "surface-container-highest": "#323537",
        "outline-variant": "#404753",
        "primary-fixed-dim": "#a5c8ff",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-secondary-container": "#adb4ce",
        "tertiary": "#7bd0ff",
        "on-secondary-fixed": "#131b2e",
        "on-primary-fixed": "#001c3a",
        "inverse-on-surface": "#2d3133",
        "secondary-container": "#3f465c",
        "on-primary-fixed-variant": "#004786",
        "on-primary": "#00315f",
        "on-surface-variant": "#c0c7d6",
        "surface-container-lowest": "#0b0f10",
        "tertiary-fixed": "#c4e7ff",
        "inverse-primary": "#005faf",
        "surface-variant": "#323537",
        "on-tertiary-fixed-variant": "#004c69",
        "background": "#101415",
        "surface": "#101415",
        "surface-bright": "#363a3b",
        "on-tertiary": "#00354a",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#bec6e0",
        "on-background": "#e0e3e5",
        "on-secondary": "#283044",
        "secondary-fixed": "#dae2fd",
        "primary-container": "#2792ff",
        "secondary": "#bec6e0",
        "outline": "#8a919f",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#191c1e",
        "inverse-surface": "#e0e3e5",
        "surface-dim": "#101415",
        "primary-fixed": "#d4e3ff",
        "on-tertiary-fixed": "#001e2c",
        "on-secondary-fixed-variant": "#3f465c",
        "on-error": "#690005",
        "on-surface": "#e0e3e5",
        "on-tertiary-container": "#002d40",
        "surface-container-high": "#272a2c",
        "tertiary-container": "#009bd1",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "container-max": "1200px",
        "section-gap": "120px",
        "gutter": "24px",
        "base": "8px",
      },
      fontFamily: {
        "hanken": ["Hanken Grotesk", "sans-serif"],
        "geist": ["Geist", "monospace"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Geist", "monospace"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "code-sm": ["Geist", "monospace"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["72px", { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["48px", { lineHeight: "56px", fontWeight: "700" }],
        "code-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "fade-in-up": "fade-in-up 0.7s ease forwards",
      },
    },
  },
  plugins: [],
};

export default config;
